### ISSUE TITLE
[Suggestion] Change name from YouTube.js

### ISSUE THREAD

**Issue by S10MC2015** [LuanRT/YouTube.js#22]
It may be a good idea to change the name from YouTube.js for legal reasons as YouTube is a trademark.

**Comment by LuanRT** [comment]
Would that really be necessary? I've seen a couple of libraries (like YouTubeDL) that have “YouTube” in their names yet Google has never taken legal action against them. Just some thoughts.

**Comment by dzek69** [comment]
I've seen some libs changing names because of legal reasons. And YouTube DL is actually bad example as it was once taken down for legal reasons, then restored but now it's basically broken for YouTube wesbite and it seems there is no real will to fix YouTube.com downloading issues (most noticeable: slow downloads).

IMO it's better to change it now, when the hype for this lib (as it seems) just started :)
