### ISSUE TITLE
[2.5.1] failed to upload video 

### ISSUE THREAD

**Issue by salman0ansari** [LuanRT/YouTube.js#250]
### Steps to reproduce

upload video example

### Failure Logs

```shell
[{"uploadStatus":{"uploadStatus":"REJECTED","message":{"runs":[{"text":"Rejected"}]},"detailedMessage":{"runs":[{"text":"Your video was rejected."}]}}},{"videoId":{"registrationStatus":"FAILED"}}]
```

### Expected behavior

upload video

### Current behavior

rejection error

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
You're most likely uploading a corrupted or invalid file. Could also be caused by a long title but I don't think that's the case here.

**Comment by salman0ansari** [comment]
> You're most likely uploading a corrupted or invalid file. It could also be caused by a long title but I don't think that's the case here.

I uploaded same video using web youtube and it uploaded without any problem and title is only 3 words long.

**Comment by LuanRT** [comment]
Can you try uploading it using the YouTube app? This library spoofs the mobile app to upload videos, it sends the exact same payloads an official client would so I still reckon it has something todo with the file itself. And IIRC all the clients do some post processing locally, so that makes it even more complicated. 

Since it's a server side thing (you only get this error message **after** the video is completely uploaded) we can't really know what YouTube considers a valid video, especially when sending a raw file.

**Comment by salman0ansari** [comment]
ok i fixed it by converting video to .mov 🤷🏻
