### ISSUE TITLE
Get nextContinuationData of YT_MUSIC 

### ISSUE THREAD

**Issue by David-Kurniawan** [LuanRT/YouTube.js#253]
### Question

Hi, thanks for the awesome package!

iam realy confuse regarding pagination workflow

i just want to get nextContinuationData and send to the next request

`has_continuation` and `getContinuation` is working great, but i want make a pagination per request

may someone can tell me how to do that?

Thanks a lot

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Heya!

I assume you are handling pagination yourself, right? If so, then all objects such as `nextContinuationData`, `reloadContinuationData` and so forth are usually available as either a `ContinuationItem` YTNode or a property of a node (as seen [in this node](https://github.com/LuanRT/YouTube.js/blob/0e5e0c0fabc75882ad9d4fba1c1a5682581e285f/src/parser/classes/SectionList.ts#L21)).

If you're dealing with `ContinuationItem` YTNodes, which are always at the very end of a list then simply calling their navigation endpoint would do:
```ts
const next_page = await target_continuation.endpoint.call(yt.actions, { parse: true, client: 'YTMUSIC' });
console.log(next_page);
```

If it is some sort of list that requires clicking a pseudo-button/text to load more items then it probably will be available as a token rather than a full `ContinuationItem` node. In this case, you can use `Actions#execute` to call it:

```ts
/**
 * NOTE: 
 * I'm using the "/next" endpoint here but it could also be "/browse".
 * Since I have no context on what you're trying to accomplish we'll use "/next".
 */
const next_page = await yt.actions.execute('/next', {
  continuation: TOKEN_GOES_HERE,
  client: 'YTMUSIC',
  parse: true
});

console.info(next_page);
```

I don't really know what kind of list you're trying to retrieve continuations from, so pardon me if this was not helpful. More context would be appreciated though.

Have a great day/night!

**Comment by David-Kurniawan** [comment]
Hi @LuanRT 

Thank you for the quick reply

Iam so sorry, i still didnt get it
let say i search for songs like this:

```
        const results = await yt.music.search(req.body.q, {
          type: req.body.shelf
        });
```

Then how i can get continuations token coz i want to send in the next request with this token then load item from the next page.

Thanks you before

**Comment by LuanRT** [comment]
Ah! Thanks for clarifying.

That should be simple, here's a small example which you can use as reference:
```ts
import { Innertube, YTNodes, Parser } from 'youtubei.js';

(async () => {
  const yt = await Innertube.create();
  
  const search = await yt.music.search('Mac Miller', { type: 'album' });
  
  const shelf = search.page.contents_memo.getType(YTNodes.MusicShelf)?.[0];
  
  let continuation_token = shelf.continuation;
  
  if (!continuation_token)
    throw new Error('Continuation not available');
    
  // Get the next page using the token:

  const page = await yt.actions.execute('/search', {
    continuation: continuation_token,
    client: 'YTMUSIC'
  });

  const data = page.data.continuationContents.musicShelfContinuation;

  const results = Parser.parse(data.contents).array().as(YTNodes.MusicResponsiveListItem);
  continuation_token = data?.continuations?.[0]?.nextContinuationData?.continuation;
  
  console.info(results, continuation_token);
})();
```

**Comment by David-Kurniawan** [comment]
Amazing, thank you so much @LuanRT , will try soon
