### ISSUE TITLE
2.7.0 Subscriptions and Trending returns `Feed {}` and Homepage seems unparsed

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#272]
### Steps to reproduce

1. Sign in
2. Call `getHomeFeed()`, `getTrending()`, or `getSubscriptionsFeed()`
3. Print the returned value

### Failure Logs

```shell
Feed {}
```

### Expected behavior

A full high-level representation of a user's selected feed.

### Current behavior

An empty object.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
It is by design - 
`Innertube#getHomeFeed()` returns a `HomeFeed` object which gives you access to everything present in the page, that is; header & contents. It also provides a set of getters for accessing shelves, videos, channels and more. The `Feed` object works the same way, the difference is that it is a generic class used to parse pages with a similar structure, hence why it may seem empty. You can access the data through the getters available.

Here's an example:
```ts
const home = await yt.getHomeFeed();
console.log('Page contents:', home.contents, '\n');
console.log('Page shelves:', home.shelves, '\n');
console.log('All videos', home.videos);
// ...
```

**Comment by walking-octopus** [comment]
Thanks! I'd close the issue now.

**Comment by walking-octopus** [comment]
Hi. Sorry for commenting on a closed issue, but `.videos`, `.contents`, and `.shelves` seem to be broken now. It returns undefined on everything. I've made sure to update to the latest version, yet the issue persists...

**Comment by walking-octopus** [comment]
Oh. Sorry. That was an issue with serialization. Sorry...

**Comment by LuanRT** [comment]
> Oh. Sorry. That was an issue with serialization. Sorry...

@walking-octopus 
No problem. Always feel free to reopen/open a new issue if you encounter any problems.
