### ISSUE TITLE
[1.4] [Quality setting not being used]

### ISSUE THREAD

**Issue by BigBalli** [LuanRT/YouTube.js#31]
## Expected Behavior

Set 1080p as video quality → 1080p video download

## Current Behavior

360p is always being downloaded regardless of quality value. I understand 360p is fallback but from video metadata I can see it supports [ '144p', '240p', '360p', '480p', '720p', '1080p' ].

## Failure Information (for bugs)
No failure, video downloads successfully but not in desired quality.
Video tried: 
    id: 'KQyXqYUdc_0',
    title: 'Rublev vs Sinner in WILD atmosphere; Tsitsipas, Zverev Feature | Monte Carlo 2022 Highlights Day 5',

## Checklist

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I have provided sufficient information

**Comment by LuanRT** [comment]
The library is choosing the 360p resolution because it is the only one available with audio, if you want higher quality videos you'll have to download video and audio separately and then merge them. So just set the type to `video` instead of `videoandaudio` and it'll download the desired quality but no audio.
