### ISSUE TITLE
Import non-exported parts of the package

### ISSUE THREAD

**Issue by KingRainbow44** [LuanRT/YouTube.js#321]
### Question

I'm trying to import classes from the package. As far as I'm concerned, you can only import them with the absolute path to the class. As of `v3.0.0`, and the change to ESModule, you can no longer import classes from the path.

Is it possible to import such classes?
An example imported classes: (and one interface)
```ts
import Music from "youtubei.js/dist/src/core/Music";
import Video from "youtubei.js/dist/src/parser/classes/Video";
import Format from "youtubei.js/dist/src/parser/classes/misc/Format";
import PlaylistVideo from "youtubei.js/dist/src/parser/classes/PlaylistVideo";
import { DownloadOptions } from "youtubei.js/dist/src/utils/FormatUtils";
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by KingRainbow44** [comment]
It's worth noting that I want to import these classes to pass them as types in my project, as well as using operations such as `instanceof` (ex: `if (track instanceof Video)`) to check types.

**Comment by absidue** [comment]
The majority of classes in YouTube.js are exported from root the library, just in a different way than most other libraries. Some might have been missed and aren't currently exported
Some of them are accessible like this:
```js
import { ClientType } from 'youtube.js';
```
Others are exported in objects that you import:
[src/parser/classes](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/classes) -> `YTNodes`
[src/parser/classes/misc](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/classes/misc) -> `Misc`
[src/parser/youtube](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/youtube) -> `YT`
[src/parser/ykids](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/ytkids) -> `YTKids`
[src/parser/ytmusic](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/ytmusic) -> `YTMusic`

Why is it like this?

- Firstly there are a bunch of class in different parts of the library that have the same names, so exporting everything directly wouldn't work without renaming them e.g. [src/parser/youtube/Channel.ts](https://github.com/LuanRT/YouTube.js/blob/main/src/parser/youtube/Channel.ts), [src/parser/classes/Channel.ts](https://github.com/LuanRT/YouTube.js/blob/main/src/parser/classes/Channel.ts) and [src/parser/ytkids/Channel.ts](https://github.com/LuanRT/YouTube.js/blob/main/src/parser/ytkids/Channel.ts)
- Secondly all of the classes in [src/parser/classes](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/classes), except in the misc folder, are named the way they are in the Innertube API responses, that is needed so that parser can correctly use the right classes, so changing any of their names would require a complete rewrite of the parser and the library, to use a matching system that uses some other system than class names to match the classes.
- Thirdly as a lot of the library is dependent on names that YouTube picks, even if the similarly named classes in other parts of the library were renamed now, more classes would likely need to be renamed in the future when YouTube picks names that conflict with other existing classes.

**Comment by KingRainbow44** [comment]
It's great that they are accessible through the root of the library, but it doesn't help when trying to pass the type as a function parameter.

Something like:
```ts
import Video from "youtubei.js/dist/src/parser/classes/Video";
import PlaylistVideo from "youtubei.js/dist/src/parser/classes/PlaylistVideo";
export function parseVideo(video: Video | PlaylistVideo)
```

would be translated to:
```ts
import { YTNodes } from "youtubei.js";
export function parseVideo(video: YTNodes.Video | YTNodes.PlaylistVideo)
```

which results in the following TypeScript error:
`TS2503: Cannot find namespace 'YTNodes'.`

Is there something that I'm missing specifically?

**Comment by absidue** [comment]
You could do something like this:
```js
import { YTNodes } from "youtubei.js";
const { Video, PlaylistVideo } = YTNodes;

export function parseVideo(video: Video | PlaylistVideo)
```

**Comment by LuanRT** [comment]
@absidue, @KingRainbow44 
This was an issue with TS not liking the way we were exporting the nodes. Should be fixed now (v3.1.0).

**Comment by absidue** [comment]
@LuanRT that change only fixes the issue for YTNodes

see https://github.com/LuanRT/YouTube.js/issues/321#issuecomment-1445122261 for everything else, also tl;dr you'll have to rename a bunch of classes before you can export them, as exporting multiple identically named Channel classes (also others but that's just the example I chose) won't work.

**Comment by LuanRT** [comment]
@absidue 
Reopening this as it may require more attention. 

I may be missing something but I tested using those classes as types and it works as expected. If you are sure that's the case, could you provide some examples?

Here's the TypeScript code I used to test this:

```ts
import { Innertube, YT, YTKids } from 'youtubei.js';

export function test1(a: YT.Channel, b: YTKids.Channel) {}

export function test2(a: YT.Channel | YTKids.Channel) {}
```

**Comment by absidue** [comment]
If it works that's great, although it should definitely be documented that the types in YouTube.js are exported that way, instead of them all being directly exported. @KingRainbow44 had to open an issue asking how to import classes and I only figured it out from digging through the source code and happening to have been involved in the refactoring pull request.
