### ISSUE TITLE
HLS Support

### ISSUE THREAD

**Issue by ronnie-codes** [LuanRT/YouTube.js#346]
### Question

I hope we can remain civilized here. My question is: How do I make hlsManifestUrl not null? Does this project support HLS or just DASH?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
The hlsManifestUrl and dashManifestUrl fields are provided by YouTube, usually they only seems to provide them for currently live live streams and currently live premiere videos. Those manifests are served from YouTube's own servers.

This library has a function, `VideoInfo#toDash`, that generates a DASH manifest for non-live/normal videos, from the array of adaptive formats that YouTube returns in their API response, the function returns the manifest XML as a string which you can then pass to a player or write to the filesystem or something.

I haven't looked into HLS very much but as I understand it, it's made up of many smaller manifests. It might be possible to generate HLS manifests, the same way that this library is capable of generating DASH manifests, however as that array of adaptive formats is intended to be used with DASH (YouTube uses DASH in there own player but they pass all the data to their player directly instead of going through an XML manifest) I don't know how well they would work with HLS.

**Comment by ChunkyProgrammer** [comment]
I think using an IOS client might make the HLS Url more frequent

**Comment by ronnie-codes** [comment]
You are correct that the `hls_manifest_url` is provided for live streams.

After taking a look at the adaptive formats, it is possible but not feasible to create an HLS manifest from what is given. The way HLS works, the "manifest" is an index of indices, and each child index contains a list of URLs to 10-second video segments. I would have to manually download each file for each resolution and then process each file into segments myself and host all of that myself and then generate indices which I would also need to host myself. Alternative solution: I am going to use a 3rd party player which supports DASH, where Apple's out of the box player does not.

Thank you both for your valuable time.

**Comment by LuanRT** [comment]
@ChunkyProgrammer is correct.

@ronnie-codes 
Feel free to open a feature request issue regarding the iOS InnerTube client if you think that would help your use case.

**Comment by ronnie-codes** [comment]
@LuanRT, I was able to leverage [f4e0f30](https://github.com/LuanRT/YouTube.js/commit/f4e0f30e6e94b347b28d67d9a86284ea2d23ee15) as my true north, and I now have proper iOS client support in place. I'll make a pull request to your repo sometime soon.

**Comment by Duell10111** [comment]
For everyone needing a code sample how to generate a hls playlist using this library, here a test repo:
https://github.com/Duell10111/yt.js-hls-proto/tree/segmentation-support

**Comment by ronnie-codes** [comment]
> For everyone needing a code sample how to generate a hls playlist using this library, here a test repo: https://github.com/Duell10111/yt.js-hls-proto/tree/segmentation-support

I forked this repo and added HLS support by simply adding an iOS client parameter a while ago. I can open a PR if anybody cares.

**Comment by Duell10111** [comment]
@ronnie-codes Does that work for any video, not only live streams?

A PR would be great for me. :)

**Comment by LuanRT** [comment]
@Duell10111 Great work on that! If this helps, using an iOS user agent or Safari context data will make InnerTube return the hls manifest (and sometimes, a hlsFormats array in the streaming data object).

**Comment by ronnie-codes** [comment]
I'll open a PR later tonight if luan wants it.

**Comment by ronnie-codes** [comment]
See https://github.com/LuanRT/YouTube.js/pull/467.
