### ISSUE TITLE
4.2.0 Empty Album authors

### ISSUE THREAD

**Issue by c0b41** [LuanRT/YouTube.js#381]
### Steps to reproduce

example code block for empty author objects, you can see result 3 don't have author.
```js
const { Innertube, YTNodes } = require('youtubei.js');

;(async () => {
  const youtube = await Innertube.create({ gl: 'US' });
  const response = await youtube.music.search(`Matilda Mann The Day That I Met You`, { type: 'album' });
  console.log(response.contents.firstOfType(YTNodes.MusicShelf).contents)
})();
```

### Failure Logs

```shell
----
```

### Expected behavior

all albums need's to return author object

### Current behavior

empty author object

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
It turns out YouTube Music doesn't return a navigation endpoint for that single (meaning the name of the artist is not clickable in the web UI) therefore we can't detect and extract the author name.

One thing we could do is expose the original flex columns, that way you'll still be able to access the artist name (but no channel id) even if the library is not able to extract it.

Relevant pieces of code:
https://github.com/LuanRT/YouTube.js/blob/ec9c0979f522469d83271f0c1b5121ef6d0c3269/src/parser/classes/MusicResponsiveListItem.ts#L215-L220

**Comment by c0b41** [comment]
yeah ı know, flex columns would work me.
