### ISSUE TITLE
Type VideoInfo["basic_info"] should overlap with type Video

### ISSUE THREAD

**Issue by Melonchanism** [LuanRT/YouTube.js#425]
### Describe your suggestion

Instead of having one have thumbnails and the other one thumbnail, it would be called the same, and instead of one having author.name and the other having one called author, they could both just have channel etc... so that they could both be used in the same scenario to get data without having to parse one to the other.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Melonchanism** [comment]
Also missing channel thumbnail in videoinfo

**Comment by absidue** [comment]
I disagree with trying to line the objects up, firstly this would be a breaking change for probably most YouTube.js users and secondly because they work completely differently.

While the channel name and id are available for both `getBasicInfo` and `getInfo`, the channel thumbnail and verified status are only available for `getInfo` (that's why you can get them from the `secondary_info` property, instead of the `basic_info` one).
