### ISSUE TITLE
Add a endpoint for todash only

### ISSUE THREAD

**Issue by Melonchanism** [LuanRT/YouTube.js#427]
### Describe your suggestion

Because some people use a backend for videoinfo to help remove unused data from being sent to the client, but still need to stream the video with dash, there should be something like `yt.toDash(id, (url) => callback)` to only get the dash manifest without getting the unnecessary data that will make it take longer to load.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
As YouTube.js generates the DASH manifest itself (YouTube only provides pregenerated ones for currently live livestreams), it needs to fetch the video information to do that. So that change won't reduce the number of requests or speed it up, it would just add another function that does the same as the existing code.

**Comment by Melonchanism** [comment]
I was able to generate it on the server
