### ISSUE TITLE
Add related videos to .getDetails func

### ISSUE THREAD

**Issue by spectrejs** [LuanRT/YouTube.js#69]
It would be great if I could get a list of videos related to a certain ID. Seems easy enough? please help.

**Comment by LuanRT** [comment]
Hi there,

Can you try the latest version? Just do:
```bash
npm install git+https://github.com/LuanRT/YouTube.js.git
```

I'm currently in the process of refactoring some things in the library and I recently added the `getInfo` method — it can retrieve pretty much everything you want and it is much faster than `getDetails`.

Note:
`getDetails` is still available but will be removed in future versions.

**Comment by PlayScriptJS** [comment]
Merci monsieur 👍

**Comment by walking-octopus** [comment]
It's not yet parsed, but I'll use it after the official release.

**Comment by walking-octopus** [comment]
`await yt.getInfo("x3IWvqMv8Ms").watch_next_feed` returns `undefined` in v2.0.2.

**Comment by absidue** [comment]
The `watch_next_feed` is always `undefined` in 2.7.0, I presume YouTube changed their layout breaking the current way of extracting it.

**Comment by LuanRT** [comment]
> The `watch_next_feed` is always `undefined` in 2.7.0, I presume YouTube changed their layout breaking the current way of extracting it.

@absidue 
It seems that the `VideoInfo` class is taking into consideration the layout of an authenticated session, but not that of an unauthenticated one. When logged in, the items of the watch next feed are inside an `ItemSection`, and along with that node will be a `RelatedChipCloud`. Something similar to this:
```
{
  secondary_results: [
    RelatedChipCloud {
      type: 'RelatedChipCloud',
      content: SuperParsedResult {}
    },
    ItemSection {
      type: 'ItemSection',
      header: null,
      contents: [Array],
      target_id: 'sid-wn-chips'
    }
}
```

An unauthenticated session's `secondary_results` array will be the watch next feed items themselves instead. No `RelatedChipCloud` and no `ItemSection`. So that's why it's `undefined` for you, it is always looking for an `ItemSection` even when it's not there:
https://github.com/LuanRT/YouTube.js/blob/22b9c174bb14f2f05edced1884e83e52b6983cba/src/parser/youtube/VideoInfo.ts#L162-L164

Honestly, I did not realize YouTube didn't allow logged out users to apply filters to that feed.

Anywho, I'll be fixing this later today. Thanks for the heads up!

**Comment by absidue** [comment]
That's weird, thanks for looking into it 🤗
