### ISSUE TITLE
Handling 401 errors

### ISSUE THREAD

**Issue by ReneMoraales** [LuanRT/YouTube.js#84]
### Question

Is there any built-in way to manage 401 Unauthorized errors? I may be missing something, but perhaps emitting an error event could help catch these errors in only one place, so we can prompt for re-authentication.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
This happens when the access token expires right when the library is still running, right? I think the problem here is that we don't trigger the `update-crendentials` event at the right time, causing InnerTube to reject the invalid token. 

So maybe we don't even need an `error` event after all, the library should handle this by itself.

Anyway, I will fix this soon. 
Thanks.

**Comment by LuanRT** [comment]
Should be fixed now, feel free to reopen this issue if it still persists. Thank you.
